server:
  port: 8700
  servlet:
    context-path: /jwt

jwt:
  itmanage:
    tokenPrefix: "ITManage"
    secret: "12345678abc"
    expireTime: 100
    header:
      alg: "HS256"
      typ: "JWT"

spring:
  web:
    resources:
      static-locations: classpath:/templates/, classpath:/static/
